name: Deploy to aws
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use java
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: "temurin"
            - name: Build with Maven
              run: mvn clean install -DSkipTests
            - name: login docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: build docker image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mini-crm:latest .
            - name: push docker image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/mini-crm:latest
